### ISSUE TITLE
建议增加看番推荐板块、新番时间表等功能

### ISSUE THREAD

**Issue by momikiii** [easybangumiorg/EasyBangumi#22]
兴致冲冲的打开了App，想刷刷有什么好看的番看，结果首页只有横向滚动的那几个番，想看新的又不知道看什么，建议增加：
新番导视，番剧推荐板块

向着全能看番App前进_(:з」∠)_

**Comment by heyanLE** [comment]
首页新需求在排期，暂时先善用搜索功能把

**Comment by AyalaKaguya** [comment]
新番时间表和看番推荐功能已经添加，由各番剧源实现
