### ISSUE TITLE
建议移除“次元城动漫”播放源

### ISSUE THREAD

**Issue by jogGUY** [easybangumiorg/EasyBangumi#26]
![Screenshot_2023-03-27-12-42-37](https://user-images.githubusercontent.com/108516858/227843328-02524c63-56ef-409e-8565-b7ce8080baab.png)
如图，其实不止主页会显示网络错误，搜索时也是显示网络错误，只是偷懒没截图
[https://www.cycdm01.top/](https://www.cycdm01.top/)这个网址打开来就提示找不到服务器IP地址，可能大概也许网站跑路了或者换域名了......

另外，“Omofun"源主页是空的，这是否正常？
![Screenshot_2023-03-27-12-45-28](https://user-images.githubusercontent.com/108516858/227843846-5e3f714b-9629-4b5e-89d4-2bc67b18636b.png)

同时，建议作者把播放源做成插件的形式，这样似乎容易维护和添加，不用靠软件更新来变更播放源

**Comment by AyalaKaguya** [comment]
你好，春春看番4.0开发中，3.0停止维护。

您说的插件化在4.0预览版中已经实现了，但是4.0的番剧源适配工作才刚刚开始，请耐心等待。

次元城动漫已经基本关闭了浏览器访问，所以基于爬虫的次元城动漫源无法正常使用；而Omofun因为API上防火墙了导致无法访问，这个问题将在4.x内解决。
