### ISSUE TITLE
播放源似乎有点问题

### ISSUE THREAD

**Issue by SCPf-166** [easybangumiorg/EasyBangumi#29]
如图，这个是播放源网站的问题还是软件问题啊
![Screenshot_2023-06-23-16-08-00-69_fc20bc637d99b7c2bbb1bdf2d0c8920b.jpg](https://github.com/easybangumiorg/EasyBangumi/assets/97646865/4dae626a-a4a1-43f3-825b-4563dbbfef4e)

![Screenshot_2023-06-23-16-08-16-56_fc20bc637d99b7c2bbb1bdf2d0c8920b.jpg](https://github.com/easybangumiorg/EasyBangumi/assets/97646865/b4dc9719-1d5a-408b-8af9-02206ad9244d)

**Comment by AyalaKaguya** [comment]
你好，根据你反馈的图片，这应该是播放源的问题，与插件作者沟通后已确认[樱花动漫](https://www.yhdmp.net)跑路，而次元城动漫的源在沟通后发现是插件有部分请求不符合规范导致被防火墙拦截的问题，请耐心等待插件作者的更新。
