### ISSUE TITLE
前来问下维护者大大，不知“次元城动漫”此扩展何时会修复？？麻烦哪位维护者大大回复下

### ISSUE THREAD

**Issue by P3R5T7U9** [easybangumiorg/EasyBangumi#31]
前几天才在github 上发现这个聚合动漫源的安卓应用，立马下载到本地安装试用，同时也加了企鹅频道和交流群；

由于提前在本仓库的Issue区翻了一些播放源相关的反馈，特别是看完 #29  这个issue后，获悉樱花动漫已跑路，所以相关的两个扩展彻底失效；

基于前车之鉴，我就只在“纯纯看番”官网的扩展仓库下载并安装“GiriGiriLove”及“次元城动漫”这两个扩展，其都为最新版，但经我测试(通过更换数个wifi和数据流量、挂上clash换了数个节点)，仅“GiriGiriLove”这个扩展可用，“次元城动漫”这个扩展还是加载失败(小声：距 #29 这个issue反馈都过去半个多月了，这个扩展的开发者还未发布修复版本)，但我这边的报错代码和 #29  这位站友所附的报错截图中代码不一样，如下：
com.google.gson.stream.MalformedJsonException Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $

为让维护者大大更清楚明白我反馈的问题，顺道贴上遇到的问题截图及扩展版本，如下：
![](https://z4a.net/images/2023/07/08/IMG_20230708_100521.jpg)
![](https://z4a.net/images/2023/07/08/IMG_20230708_104025.jpg)

我今早最初在交流群里反馈了这个问题，但一直没有哪个管理员回复“次元城动漫”这个扩展何时修复，随后有群友却回复他那边一直可用这个扩展，原因就很迷，也贴上当时的交流情况，如下：
![](https://z4a.net/images/2023/07/08/IMG_20230708_105142.jpg)

特开此issue，麻烦哪个维护者大大来回复我遇到的这个问题，为何群友可用此扩展，而我尝试各种网络环境，依旧加载报错😭

**Comment by even0306** [comment]
https://github.com/easybangumiorg/EasyBangumi/issues/29#issuecomment-1606647330

**Comment by P3R5T7U9** [comment]
> [#29 (comment)](https://github.com/easybangumiorg/EasyBangumi/issues/29#issuecomment-1606647330)
emmm，，，刚才看到我开的这条issue有新回复了，在打开查看前，还以为是此仓库的维护者之一来回复了，打开一查看，老哥你回复内容是指路此仓库的第29条issue，然而我当初在反馈时，就引用过这条issue。。。
(小声：顺道说下，我在创建某个仓库的issue前，必会先阅览几遍该仓库的旧issue，以便了解我想反馈的问题，网友们在之前有无反馈过，所以对老哥你这条简短的回复略微有些小失望😖)

感觉老哥你回复的内容，感觉是不是在发回复之前，未将我反馈的内容从头到尾看完，从而误理解我反馈内容想表达的真正想法？？我在原反馈内容中就引用过第29条这个issue，早已了解“次元城动漫”这个扩展由于官方服务器防火墙拦截原因，可能访问报错；

但我在反馈内容的最后也提到用户交流群里有一些群友反馈这个扩展可用，而且这些群友都回复说没有挂梯，直连就可以正常访问“次元城动漫”。。。但我无论换了好几个网络情况，还挂梯换了一些节点访问，依旧报错，所以特此开这个issue向维护者反馈下，主要就是想蹲某个维护者来回复一些群友可正常访问这个扩展，而我这边一直访问报错这个问题的深层原因；还有就是再问问维护者，“次元城动漫”这个扩展到底何时会彻底修复，有些等不急[doge]
（小声：如果老哥你在发回复前，先从头到尾认真看完我反馈的内容，多看几遍，可能就不会只发简短的回复，感觉老哥你的回复有些答非所问😓）

**Comment by heyanLE** [comment]
1. 次元城所用的服务器在国内是属于锁区的状态（比如福建），
2. 次元城官方估计用了一些代理魔法让他们app能用，但是因为他们app使用flutter开发，无法反编译，这部分暂时解不了
3. 因此次元城插件暂时无法修复，后面会出更多源来让更多人有源可用

**Comment by heyanLE** [comment]
1. 次元城所用的服务器在国内是属于锁区的状态（比如福建），
2. 次元城官方估计用了一些代理魔法让他们app能用，但是因为他们app使用flutter开发，无法反编译，这部分暂时解不了
3. 因此次元城插件暂时无法修复，后面会出更多源来让更多人有源可用

**Comment by P3R5T7U9** [comment]
> 1. 次元城所用的服务器在国内是属于锁区的状态（比如福建），
> 2. 次元城官方估计用了一些代理魔法让他们app能用，但是因为他们app使用flutter开发，无法反编译，这部分暂时解不了
> 3. 因此次元城插件暂时无法修复，后面会出更多源来让更多人有源可用

抱歉我回复迟了，前两天忙其它事，一直没注意到回复提醒通知邮件😖

感谢何大详细回复“次元城动漫”这个扩展暂时无法修复的原因，但我在原反馈内容还问到“为何这个扩展在用户交流群里有些群友一直可用，我这边一直访问报错”，相关交流截图也附在原反馈末尾，这个问题何大貌似没注意到，何大有时间的话，麻烦也回复下我这个问题呗[小纠结]
