### ISSUE TITLE
[BUG] 视频加载完成后加载进度条无法消失

### ISSUE THREAD

**Issue by fankes** [easybangumiorg/EasyBangumi#32]
复现过程：
在首页随意点击一个番剧，进入详情页面，加载进度条消失后开始播放，此时没有问题，但是点击横屏按钮后加载进度条重新出现，且退出横屏也依然存在于屏幕中央，不知道是否只有我存在这样的问题。

软件版本：4.1.0
系统版本：Android 12 (MIUI)

**Comment by GOI4C** [comment]
我也有

**Comment by fankes** [comment]
更新到 5.x 版本该问题已经修复了
