### ISSUE TITLE
请教下这种扩展插件化项目用得什么框架啊

### ISSUE THREAD

**Issue by f262866551** [easybangumiorg/EasyBangumi#35]
如题，我手头上也有个项目需要用到类似得技术，能说下实现框架或者技术么，谢谢

**Comment by AyalaKaguya** [comment]
你好，关于纯纯看番的插件化的实现原理，可以参照 https://github.com/easybangumiorg/EasyBangumi/tree/main/extension 目录下的源代码，但是近期相关代码可能会产生迁移，请注意版本变化。

**Comment by heyanLE** [comment]
可以看 extension 模块和 source 模块的相关代码
