### ISSUE TITLE
功能需求 代理

### ISSUE THREAD

**Issue by axlmly** [easybangumiorg/EasyBangumi#41]
win11子系统上安装，直接开代理无效，所以能在软件里面加个能使用局域网内其他设备的代理配置吗。socks http那种

**Comment by artiga033** [comment]
WSA的话虽然无法使用windows的系统代理，但是可以直接在子系统中运行基于Android VPN的代理软件 虽然wsa没有vpn权限弹窗但可以通过`adb shell appops set [package name] ACTIVATE_VPN allow`授权

参考 <https://github.com/riverar/wsa-app-compatibility#vpn>
