### ISSUE TITLE
功能建议: 选集倒序排列

### ISSUE THREAD

**Issue by Weidows** [easybangumiorg/EasyBangumi#43]
如题一个小改动, 有的动漫集数比较多(海贼王), 翻起来好半天
(app好用, 赞一个先👍)

**Comment by heyanLE** [comment]
已经有的哈，这里正序点击就是倒序
![Screenshot_2024-01-30-10-44-01-83_fc20bc637d99b7c2bbb1bdf2d0c8920b.jpg](https://github.com/easybangumiorg/EasyBangumi/assets/17961056/bb3e8488-4057-482a-9496-d2eefc322622)

**Comment by Weidows** [comment]
那可能还有点bug, 我试了几个动漫点了点, 顺序都没变化
