### ISSUE TITLE
功能需求 支持载入在线弹幕

### ISSUE THREAD

**Issue by thouser8** [easybangumiorg/EasyBangumi#50]
这个功能应该可以通过弹弹play插件实现，目前我在使用的emby和一些在线网站都通过此方法实现了弹幕支持，例如这个项目：https://github.com/IronKinoko/agefans-enhance

**Comment by AyalaKaguya** [comment]
你好，感谢提出建议，资源刮削与弹幕匹配是计划中的功能，但是纯纯看番5.x版本目前的开发计划可能无法达到预期，你可以等待纯纯看番6.x版本或者关注早期仓库提交，当前版本仍然有一些bug需要修复。

**Comment by thouser8** [comment]
> 你好，感谢提出建议，资源刮削与弹幕匹配是计划中的功能，但是纯纯看番5.x版本目前的开发计划可能无法达到预期，你可以等待纯纯看番6.x版本或者关注早期仓库提交，当前版本仍然有一些bug需要修复。

了解了，忠心感谢开发团队🙏
