### ISSUE TITLE
armeabi-v7a这个支持安卓tv吗？

### ISSUE THREAD

**Issue by Amazon90** [easybangumiorg/EasyBangumi#57]
easybangumi-armeabi-v7a
这个版本对安卓电视有支持吗？

**Comment by AyalaKaguya** [comment]
你好，安卓tv无法确定具体指令集架构，请使用easybangumi-universal这个版本，该版安装包体积较大但是能提供最大程度的兼容性。

**Comment by Amazon90** [comment]
> 你好，安卓tv无法确定具体指令集架构，请使用easybangumi-universal这个版本，该版安装包体积较大但是能提供最大程度的兼容性。

感谢，今天回家试试看电视能不能支持，如果可以就太好了，会是我认为的电视上最棒的追番神器😁

**Comment by shenmintao** [comment]
<img width="1839" height="628" alt="Image" src="https://github.com/user-attachments/assets/3c176d59-0c54-4804-b5f0-837b81def408" />
你好，我自己改了一版可以用遥控器操作的界面，除了有点丑之外功能应该都是好的

**Comment by Amazon90** [comment]
> <img width="1839" height="628" alt="Image" src="https://github.com/user-attachments/assets/3c176d59-0c54-4804-b5f0-837b81def408" />
> 你好，我自己改了一版可以用遥控器操作的界面，除了有点丑之外功能应该都是好的

能用的就是好软件👍

**Comment by Amazon90** [comment]
> <img width="1839" height="628" alt="Image" src="https://github.com/user-attachments/assets/3c176d59-0c54-4804-b5f0-837b81def408" />
> 你好，我自己改了一版可以用遥控器操作的界面，除了有点丑之外功能应该都是好的

Release是空的，在哪儿下载apk？

**Comment by shenmintao** [comment]
@Amazon90 在Action里面，我上传到网盘了
链接: https://pan.baidu.com/s/1lRIt0vHuzDqFN4Vz-MeMmg?pwd=igg6 提取码: igg6

**Comment by Amazon90** [comment]
> @Amazon90 在Action里面，我上传到网盘了
> 链接: https://pan.baidu.com/s/1lRIt0vHuzDqFN4Vz-MeMmg?pwd=igg6 提取码: igg6 

谢谢，希望后续有更新能release里发，可以手机上下载，action在手机端看不见。
