### ISSUE TITLE
转码进度显示异常

### ISSUE THREAD

**Issue by TCOTC** [easybangumiorg/EasyBangumi#61]
这个初看还挺离谱的：

![Screenshot_2024-05-10-01-41-22-32_fc20bc637d99b7c2bbb1bdf2d0c8920b.jpg](https://github.com/easybangumiorg/EasyBangumi/assets/78434827/ddc21b4b-cea2-4b36-9620-5e6478b76e90)

**Comment by heyanLE** [comment]
只是显示错误吗，有没有正常转码成功

**Comment by TCOTC** [comment]
只有显示错误，其他正常
