### ISSUE TITLE
v5.2.3 拓展无法安装

### ISSUE THREAD

**Issue by TCOTC** [easybangumiorg/EasyBangumi#65]
![Screenshot_2024-06-01-21-29-02-53_fc20bc637d99b7c2bbb1bdf2d0c8920b.jpg](https://github.com/easybangumiorg/EasyBangumi/assets/78434827/943505d4-bca4-468f-82b7-229cf5685cca)

---

![Screenshot_2024-06-01-21-30-35-54_fc20bc637d99b7c2bbb1bdf2d0c8920b.jpg](https://github.com/easybangumiorg/EasyBangumi/assets/78434827/171e2c82-16f4-407a-8277-eb7b04c987a8)

**Comment by heyanLE** [comment]
重启看看，安装新版源看看

**Comment by TCOTC** [comment]
录屏：

https://github.com/easybangumiorg/EasyBangumi/assets/78434827/f3c8493a-745e-497d-a579-e11deacfbeeb

**Comment by TCOTC** [comment]
突然就可以更新 1.5 了
