### ISSUE TITLE
[5.4.1] 更新后标签丢失

### ISSUE THREAD

**Issue by TCOTC** [easybangumiorg/EasyBangumi#69]
5.4.1

![Screenshot_2024-07-16-02-59-45-42_fc20bc637d99b7c2bbb1bdf2d0c8920b.jpg](https://github.com/user-attachments/assets/c7306c3d-bb12-40c0-bd16-d34ee4e02d39)

**Comment by TCOTC** [comment]
那个筛选好像没用

**Comment by heyanLE** [comment]
> 5.4.1
> 
> ![Screenshot_2024-07-16-02-59-45-42_fc20bc637d99b7c2bbb1bdf2d0c8920b.jpg](https://github.com/user-attachments/assets/c7306c3d-bb12-40c0-bd16-d34ee4e02d39)
> 
> 

筛选关掉

**Comment by TCOTC** [comment]
也不行

![Screenshot_2024-07-16-12-45-08-19_fc20bc637d99b7c2bbb1bdf2d0c8920b.jpg](https://github.com/user-attachments/assets/1752f6fa-430f-48a6-b034-fddf78b58861)

**Comment by heyanLE** [comment]
去标签管理页面看看，可能是你只开了某个没有番的标签

**Comment by TCOTC** [comment]
标签变成这样了，旧标签都消失了：

![aaf217bd6f1170f84a507655d74066e](https://github.com/user-attachments/assets/23e32b80-320c-44b9-a695-f6b7425ff3a3)

**Comment by TCOTC** [comment]
5.4.3 更新后标签回来了
