### ISSUE TITLE
[BUG]: PreferenceHelper 有问题

### ISSUE THREAD

**Issue by refgd** [easybangumiorg/EasyBangumi#82]
### 系统

Android 14

### 纯纯看番版本号

5.4.4

### 发生了什么？

每次新启动的时候，如果是直接打开主页，PreferenceHelper读取的都是空的，如果是打开后在其它界面再跳转到主页，就能读取到数据，可能是如果启动后直接打开主页，这时候PreferenceHelper还没初始化完成

**Comment by AyalaKaguya** [comment]
PreferenceHelper.get(tag,default) 
默认获取到的是第二个参数，除非用户打开插件设置进行修改，在这之前可以看作PreferenceComponent没有加载
