### ISSUE TITLE
[BUG]: 多次添加js插件，不会覆盖，会建立新的文件

### ISSUE THREAD

**Issue by refgd** [easybangumiorg/EasyBangumi#89]
### 系统

Android 15

### 发生了什么？

多次添加js插件，不会覆盖，会建立新的文件，导致删除需要进行多次删除，也会多次加载插件

**Comment by AyalaKaguya** [comment]
该问题在提交[d2c383b](https://github.com/easybangumiorg/EasyBangumi/commit/d2c383bdc3ac1c6f662cb8679b0a70ec441f3898)中已得到修复，将在下个版本更新。
